### Linear regression
### y = A*x + B
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Linear_least_squares_example2.svg/1280px-Linear_least_squares_example2.svg.png" width="400">

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [1]:
class LinearRegression:
    def __init__(self):
        self.slope = None
        self.intercept = None
    
    def fit(self, X, y):
        pass

    def predict(self, X):
        pass
        return y_pred

In [ ]:
np.random.seed(42)
X_train = 2 * np.random.rand(100)
y_train = 4 + 3 * X_train + np.random.randn(100)

model = LinearRegression()
model.fit(____, ____)

y_fit = model.predict(____)
X_test = ____
predictions = model.predict(____)

print(f"Slope: {model.slope:.2f}")
print(f"Intercept: {model.intercept:.2f}")
print(f"Predictions X={X_test}: {predictions}")

In [ ]:
plt.scatter(____, ____, label="True")
plt.plot(____, ____, label="Fit")
plt.scatter(____, ____, 'r', label="Prediction")
plt.show()

# Personal task

* Implement the MSE loss function.
* Implement the Linear Regression model. Function: $R^n$ -> $R$.
* Download the Diabetes Dataset and describe its features with pandas and histograms.
* Split your dataset into 80%/20% train/test sets.
* Normalize the data with mean and standard deviation.
* Train and test your model. You should predict the **target** variable by the **features**. Use the MSE loss for testing.

In [18]:
import pandas as pd
from sklearn.datasets import load_diabetes
diabetes = load_diabetes(scaled=False)

In [23]:
diabetes_df = pd.DataFrame(
    data=diabetes.data,
    columns=diabetes.feature_names
)

target_df = pd.DataFrame(
    data=diabetes.target,
    columns=["target"])
diabetes_df

      age  sex   bmi      bp     s1     s2    s3    s4      s5     s6
0    59.0  2.0  32.1  101.00  157.0   93.2  38.0  4.00  4.8598   87.0
1    48.0  1.0  21.6   87.00  183.0  103.2  70.0  3.00  3.8918   69.0
2    72.0  2.0  30.5   93.00  156.0   93.6  41.0  4.00  4.6728   85.0
3    24.0  1.0  25.3   84.00  198.0  131.4  40.0  5.00  4.8903   89.0
4    50.0  1.0  23.0  101.00  192.0  125.4  52.0  4.00  4.2905   80.0
..    ...  ...   ...     ...    ...    ...   ...   ...     ...    ...
437  60.0  2.0  28.2  112.00  185.0  113.8  42.0  4.00  4.9836   93.0
438  47.0  2.0  24.9   75.00  225.0  166.0  42.0  5.00  4.4427  102.0
439  60.0  2.0  24.9   99.67  162.0  106.6  43.0  3.77  4.1271   95.0
440  36.0  1.0  30.0   95.00  201.0  125.2  42.0  4.79  5.1299   85.0
441  36.0  1.0  19.6   71.00  250.0  133.2  97.0  3.00  4.5951   92.0

[442 rows x 10 columns]

In [24]:
target_df

     target
0     151.0
1      75.0
2     141.0
3     206.0
4     135.0
..      ...
437   178.0
438   104.0
439   132.0
440   220.0
441    57.0

[442 rows x 1 columns]

In [ ]:
def mse_loss(y_true, y_pred):
    pass


class LinearRegression:
    def __init__(self):
        self.slope = None
        self.intercept = None
    
    def fit(self, X, y):
        pass

    def predict(self, X):
        pass